repos:
- repo: meta
  hooks:
    - id: check-hooks-apply
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-ast
    - id: check-builtin-literals
    - id: check-byte-order-marker
    - id: check-docstring-first
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
      args: ['--remove']
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: trailing-whitespace
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
    - id: black
- repo: https://github.com/asottile/pyupgrade
  rev: v2.7.2
  hooks:
    - id: pyupgrade
      args: ['--py37-plus']
